# Chapter2 PyTorchの基本
## 1. テンソル（TENSOR）

In [ ]:
# 必要なパッケージをインポート
import torch
import numpy as np

## 1.1. Tensorの生成

In [ ]:
# listを渡してTensorを生成
x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [ ]:
# listを入れ子にしてTensorを生成
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.size())  # Tensorの形状を確認

torch.Size([2, 3])


In [ ]:
# データ型を指定せずにTensorを生成
x1 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# dtypeを指定して64ビット浮動小数点数型のTensorを生成
x2 = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float64)

# torchのメソッドから64ビット浮動小数点数型のTensorを生成
x3 = torch.DoubleTensor([[1, 2, 3], [4, 5, 6]])

# dtypeの確認
print(x1.dtype)  # データ型指定なし
print(x2.dtype)  # データ型指定
print(x3.dtype)  # データ型指定

torch.int64
torch.float64
torch.float64


In [ ]:
# 0から9までの1次元Tensorを生成
x = torch.arange(0, 10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
# 0から始まって9まで2ずつ増えていく1次元Tensorを生成
x = torch.linspace(0, 9, 5)
print(x)

tensor([0.0000, 2.2500, 4.5000, 6.7500, 9.0000])


In [ ]:
# 0から1の間の乱数を生成
x = torch.rand(2, 3)
print(x)

tensor([[0.4500, 0.7987, 0.7259],
        [0.0492, 0.1459, 0.1227]])


In [ ]:
# 2x3の零テンソルを生成
x = torch.zeros(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# 形状が2x3で要素がすべて1のテンソルを生成
x = torch.ones(2, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
x = torch.tensor([1, 2, 3]).to('cuda')
print(x.device)

cuda:0


## 1.2. Tensorとndarrayの変換

In [ ]:
# ndarrayの生成
array = np.array([[1,2,3],[4,5,6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# ndarrayからTensorへ変換
tensor = torch.from_numpy(array)
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# Tensorからndarrayへ変換
tensor2array = tensor.numpy()
print(tensor2array)

[[1 2 3]
 [4 5 6]]


## 1.3. Tensorの操作

In [ ]:
# インデックスの指定
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[1, 2])

tensor(6)


In [ ]:
# スライスで要素を取得
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[1, :])

tensor([4, 5, 6])


In [ ]:
# 2x3から3x2のTensorに変換
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x_reshape = x.view(3, 2)
print(x)  # 変換前の2x3のTensor
print(x_reshape)  # 変換後の3x2のTensor

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


## 1.4. Tensorの演算

In [ ]:
# Tensorとスカラーの四則演算
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float64)
print(x + 2)  # 足し算
print(x - 2)  # 引き算
print(x * 2)  # 掛け算
print(x / 2)  # 足し算

tensor([[3., 4., 5.],
        [6., 7., 8.]], dtype=torch.float64)
tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]], dtype=torch.float64)
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], dtype=torch.float64)
tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]], dtype=torch.float64)


In [ ]:
# Tensor同士の四則演算
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float64)
y = torch.tensor([[4, 5, 6], [7, 8, 9]], dtype=torch.float64)
print(x + y)  # 足し算
print(x - y)  # 引き算
print(x * y)  # 掛け算
print(x / y)  # 割り算

tensor([[ 5.,  7.,  9.],
        [11., 13., 15.]], dtype=torch.float64)
tensor([[-3., -3., -3.],
        [-3., -3., -3.]], dtype=torch.float64)
tensor([[ 4., 10., 18.],
        [28., 40., 54.]], dtype=torch.float64)
tensor([[0.2500, 0.4000, 0.5000],
        [0.5714, 0.6250, 0.6667]], dtype=torch.float64)


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float64)
print(torch.min(x))  # 最小値
print(torch.max(x))  # 最大値
print(torch.mean(x))  # 平均値
print(torch.sum(x))  # 合計値

tensor(1., dtype=torch.float64)
tensor(6., dtype=torch.float64)
tensor(3.5000, dtype=torch.float64)
tensor(21., dtype=torch.float64)


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float64)
print(torch.sum(x).item())  # 合計値

21.0
